//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAssignment1Service")]
    public interface IAssignment1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/checkPrime", ReplyAction="http://tempuri.org/IAssignment1Service/checkPrimeResponse")]
        bool checkPrime(int n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/checkPrime", ReplyAction="http://tempuri.org/IAssignment1Service/checkPrimeResponse")]
        System.Threading.Tasks.Task<bool> checkPrimeAsync(int n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/sumDigits", ReplyAction="http://tempuri.org/IAssignment1Service/sumDigitsResponse")]
        int sumDigits(int n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/sumDigits", ReplyAction="http://tempuri.org/IAssignment1Service/sumDigitsResponse")]
        System.Threading.Tasks.Task<int> sumDigitsAsync(int n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/reverseString", ReplyAction="http://tempuri.org/IAssignment1Service/reverseStringResponse")]
        string reverseString(string n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/reverseString", ReplyAction="http://tempuri.org/IAssignment1Service/reverseStringResponse")]
        System.Threading.Tasks.Task<string> reverseStringAsync(string n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/joinString", ReplyAction="http://tempuri.org/IAssignment1Service/joinStringResponse")]
        string joinString(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/joinString", ReplyAction="http://tempuri.org/IAssignment1Service/joinStringResponse")]
        System.Threading.Tasks.Task<string> joinStringAsync(string s1, string s2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/sortNumber", ReplyAction="http://tempuri.org/IAssignment1Service/sortNumberResponse")]
        int[] sortNumber(int[] a1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/sortNumber", ReplyAction="http://tempuri.org/IAssignment1Service/sortNumberResponse")]
        System.Threading.Tasks.Task<int[]> sortNumberAsync(int[] a1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/sortNumberDesc", ReplyAction="http://tempuri.org/IAssignment1Service/sortNumberDescResponse")]
        int[] sortNumberDesc(int[] a1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment1Service/sortNumberDesc", ReplyAction="http://tempuri.org/IAssignment1Service/sortNumberDescResponse")]
        System.Threading.Tasks.Task<int[]> sortNumberDescAsync(int[] a1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssignment1ServiceChannel : AssignmentClient.ServiceReference1.IAssignment1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment1ServiceClient : System.ServiceModel.ClientBase<AssignmentClient.ServiceReference1.IAssignment1Service>, AssignmentClient.ServiceReference1.IAssignment1Service {
        
        public Assignment1ServiceClient() {
        }
        
        public Assignment1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkPrime(int n1) {
            return base.Channel.checkPrime(n1);
        }
        
        public System.Threading.Tasks.Task<bool> checkPrimeAsync(int n1) {
            return base.Channel.checkPrimeAsync(n1);
        }
        
        public int sumDigits(int n1) {
            return base.Channel.sumDigits(n1);
        }
        
        public System.Threading.Tasks.Task<int> sumDigitsAsync(int n1) {
            return base.Channel.sumDigitsAsync(n1);
        }
        
        public string reverseString(string n1) {
            return base.Channel.reverseString(n1);
        }
        
        public System.Threading.Tasks.Task<string> reverseStringAsync(string n1) {
            return base.Channel.reverseStringAsync(n1);
        }
        
        public string joinString(string s1, string s2) {
            return base.Channel.joinString(s1, s2);
        }
        
        public System.Threading.Tasks.Task<string> joinStringAsync(string s1, string s2) {
            return base.Channel.joinStringAsync(s1, s2);
        }
        
        public int[] sortNumber(int[] a1) {
            return base.Channel.sortNumber(a1);
        }
        
        public System.Threading.Tasks.Task<int[]> sortNumberAsync(int[] a1) {
            return base.Channel.sortNumberAsync(a1);
        }
        
        public int[] sortNumberDesc(int[] a1) {
            return base.Channel.sortNumberDesc(a1);
        }
        
        public System.Threading.Tasks.Task<int[]> sortNumberDescAsync(int[] a1) {
            return base.Channel.sortNumberDescAsync(a1);
        }
    }
}
